//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GTimeTable
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GTimeTableEntities : DbContext
    {
        public GTimeTableEntities()
            : base("name=GTimeTableEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<WorkingDaysPerWeek> WorkingDaysPerWeeks { get; set; }
        public virtual DbSet<WorkingTimePerDay> WorkingTimePerDays { get; set; }
        public virtual DbSet<TimeTableSlot> TimeTableSlots { get; set; }
        public virtual DbSet<WorkingDay> WorkingDays { get; set; }
    }
}
