//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GTimeTable
{
    using System;
    using System.Collections.Generic;
    
    public partial class LecturesSession
    {
        public int id { get; set; }
        public int lecture { get; set; }
        public int session { get; set; }
    
        public virtual Lecturer Lecturer { get; set; }
        public virtual Session Session1 { get; set; }
    }
}
