//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GTimeTable
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room
    {
        public int id { get; set; }
        public int capacity { get; set; }
        public string roomId { get; set; }
        public string roomType { get; set; }
        public int building { get; set; }
    
        public virtual Building Building1 { get; set; }
    }
}
