//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GTimeTable
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Room()
        {
            this.SutiableTabforRooms = new HashSet<SutiableTabforRoom>();
            this.SuitableRoomsforSubjectTags = new HashSet<SuitableRoomsforSubjectTag>();
            this.SuitableRoomsforLecturers = new HashSet<SuitableRoomsforLecturer>();
            this.SuiableRoomsforSessions = new HashSet<SuiableRoomsforSession>();
            this.SuitableRoomsforGroups = new HashSet<SuitableRoomsforGroup>();
        }
    
        public int id { get; set; }
        public int capacity { get; set; }
        public string roomId { get; set; }
        public string roomType { get; set; }
        public int building { get; set; }
    
        public virtual Building Building1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SutiableTabforRoom> SutiableTabforRooms { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SuitableRoomsforSubjectTag> SuitableRoomsforSubjectTags { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SuitableRoomsforLecturer> SuitableRoomsforLecturers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SuiableRoomsforSession> SuiableRoomsforSessions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SuitableRoomsforGroup> SuitableRoomsforGroups { get; set; }
    }
}
