//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GTimeTable
{
    using System;
    using System.Collections.Generic;
    
    public partial class Session
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Session()
        {
            this.LecturesSessions = new HashSet<LecturesSession>();
            this.NotAvailbeleTimesOfSessions = new HashSet<NotAvailbeleTimesOfSession>();
            this.SuiableRoomsforSessions = new HashSet<SuiableRoomsforSession>();
            this.ParrelalSessions = new HashSet<ParrelalSession>();
        }
    
        public int id { get; set; }
        public int count { get; set; }
        public string duration { get; set; }
        public int subject { get; set; }
        public int tag { get; set; }
        public int student { get; set; }
        public Nullable<int> consecutive_session_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LecturesSession> LecturesSessions { get; set; }
        public virtual Student Student1 { get; set; }
        public virtual Subject Subject1 { get; set; }
        public virtual Tag Tag1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NotAvailbeleTimesOfSession> NotAvailbeleTimesOfSessions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SuiableRoomsforSession> SuiableRoomsforSessions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ParrelalSession> ParrelalSessions { get; set; }
    }
}
