//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GTimeTable
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subject
    {
        public int id { get; set; }
        public string name { get; set; }
        public string code { get; set; }
        public int off_year { get; set; }
        public int off_sem { get; set; }
        public int lec_hrs { get; set; }
        public int tute_hrs { get; set; }
        public int lab_hrs { get; set; }
        public int eval_hrs { get; set; }
    }
}
