//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GTimeTable
{
    using System;
    using System.Collections.Generic;
    
    public partial class SuitableRoomsforGroup
    {
        public int id { get; set; }
        public int group_id { get; set; }
        public int room { get; set; }
    
        public virtual Room Room1 { get; set; }
        public virtual Student Student { get; set; }
    }
}
