//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GTimeTable
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkingDaysAndHour
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WorkingDaysAndHour()
        {
            this.WorkingDaysOfWeeks = new HashSet<WorkingDaysOfWeek>();
        }
    
        public int id { get; set; }
        public string slots_for_time_table { get; set; }
        public Nullable<int> no_of_working_days { get; set; }
        public Nullable<int> working_time_per_day { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkingDaysOfWeek> WorkingDaysOfWeeks { get; set; }
    }
}
